variable "rg_name" {
  type        = string
  description = "A predefined resource group in the Azure subscription."
}

variable "location" {
  type        = string
  description = "The Azure region to deploy all resources to."
}

variable "instance_type" {
  type        = string
  description = "The virtual machine type (sku) to deploy."
}

variable "protocol" {
  type        = string
  description = "Name of the protocol."
  default     = "NFS"

  validation {
    condition     = contains(["NFS", "SMB"], var.protocol)
    error_message = "Allowed values for protocol: NFS, SMB."
  }
}

variable "secondary_ips_per_nic" {
  type        = number
  description = "Number of secondary IPs per single NIC per protocol gateway virtual machine."
  default     = 0

  # validation {
  #   condition     = var.secondary_ips_per_nic >= 1
  #   error_message = "The number of secondary IPs per single NIC per protocol gateway virtual machine must be at least 1."
  # }
}

variable "vnet_rg_name" {
  type        = string
  description = "Resource group name of vnet"
}

variable "vnet_name" {
  type        = string
  description = "The virtual network name."
}

variable "subnet_name" {
  type        = string
  description = "The subnet names."
}

variable "tags_map" {
  type        = map(string)
  default     = {}
  description = "A map of tags to assign the same metadata to all resources in the environment. Format: key:value."
}

variable "gateways_number" {
  type        = number
  description = "The number of virtual machines to deploy as protocol gateways."
}

variable "gateways_name" {
  type        = string
  description = "The protocol group name."
}

variable "interface_group_name" {
  type        = string
  description = "Interface group name."
  default     = "weka-ig"

  validation {
    condition     = length(var.interface_group_name) <= 11
    error_message = "The interface group name should be up to 11 characters long."
  }
}

variable "client_group_name" {
  type        = string
  description = "Client access group name."
  default     = "weka-cg"
}

variable "backend_lb_ip" {
  type        = string
  description = "The backend load balancer ip address."
}

variable "vm_username" {
  type        = string
  description = "The user name for logging in to the virtual machines."
  default     = "weka"
}

variable "ssh_public_key" {
  type        = string
  description = "The VM public key. If it is not set, the keys are auto-generated."
}

variable "assign_public_ip" {
  type        = bool
  default     = true
  description = "Determines whether to assign public ip."
}

variable "ppg_id" {
  type        = string
  description = "Placement proximity group id."
}

variable "sg_id" {
  type        = string
  description = "Security group id."
}

variable "source_image_id" {
  type        = string
  description = "Use weka custom image, ubuntu 20.04 with kernel 5.4 and ofed 5.8-1.1.2.1"
}

variable "apt_repo_server" {
  type        = string
  default     = ""
  description = "The URL of the apt private repository."
}

variable "disk_size" {
  type        = number
  description = "The disk size."
}

variable "traces_per_frontend" {
  default     = 10
  type        = number
  description = "The number of traces per frontend ionode. Traces are low-level events generated by Weka processes and are used as troubleshooting information for support purposes. Protocol gateways have only frontend ionodes."
}

variable "frontend_container_cores_num" {
  type        = number
  default     = 1
  description = "The number of frontend ionodes per instance."

  validation {
    condition     = var.frontend_container_cores_num >= 1
    error_message = "The number of frontend ionodes per GW instance must be at least 1."
  }
}

variable "install_weka_url" {
  type        = string
  description = "The URL of the Weka release download tar file."

  validation {
    condition     = length(var.install_weka_url) > 0
    error_message = "The URL should not be empty."
  }
}
variable "key_vault_url" {
  type        = string
  description = "The URL of the Azure Key Vault."
}

variable "key_vault_id" {
  type        = string
  description = "The id of the Azure Key Vault."
}

variable "setup_protocol" {
  type        = bool
  description = "Configure protocol, default value is False"
}

variable "smbw_enabled" {
  type        = bool
  default     = false
  description = "Enable SMBW protocol."
}

variable "smb_cluster_name" {
  type        = string
  description = "The name of the SMB setup."
  default     = "Weka-SMB"

  validation {
    condition     = length(var.smb_cluster_name) > 0 && length(var.smb_cluster_name) <= 15
    error_message = "The SMB cluster name should be less than 15 characters long."
  }
}

variable "smb_domain_name" {
  type        = string
  description = "The domain to join the SMB cluster to."
  default     = ""
}

variable "smb_domain_netbios_name" {
  type        = string
  description = "The domain NetBIOS name of the SMB cluster."
  default     = ""
}

variable "smb_dns_ip_address" {
  type        = string
  description = "DNS IP address"
  default     = ""
}

variable "smb_share_name" {
  type        = string
  description = "The name of the SMB share"
  default     = ""
}

variable "weka_tar_storage_account_id" {
  type    = string
  default = ""
}

variable "function_app_name" {
  type        = string
  description = "The name of the function app."

  validation {
    condition     = length(var.function_app_name) > 0
    error_message = "The function app name should not be empty."
  }
}

variable "vault_function_app_key_name" {
  type        = string
  description = "The name of the Vault key containing the function app key."
  default     = "function-app-default-key"
}
